# aws cloudformation deploy --stack-name Dart-network-002 --template 002-network.cfn.yml

# aws cloudformation validate-template --template-body file://002-network.cfn.yml
# aws cloudformation delete-stack --stack-name Dart-network-102

Resources:
  DartVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.35.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true      

  DartVPCIpv6CidrBlock: # Esse cara aqui garante que a VPC vai permitir usarmos IPV6
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      VpcId: !Ref DartVPC
      AmazonProvidedIpv6CidrBlock: true 

  DartSNPrivA:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Select [ 0, !Cidr [ !Select [ 0, !GetAtt DartVPC.Ipv6CidrBlocks], 8, 64 ]] # vamos gerar 8 subnets ipv6 e vamos pegar a primeira
      CidrBlock: 172.35.10.0/24
      VpcId: !Ref DartVPC
      AvailabilityZone: !Select 
        - 0 
        - !GetAZs
          Ref: 'AWS::Region'

  DartSNPrivB:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Select [ 1, !Cidr [ !Select [ 0, !GetAtt DartVPC.Ipv6CidrBlocks], 8, 64 ]] # vamos gerar 8 subnets ipv6 e vamos pegar a segunda
      CidrBlock: 172.35.11.0/24
      VpcId: !Ref DartVPC
      AvailabilityZone: !Select 
        - 1
        - !GetAZs
          Ref: 'AWS::Region'

  DartSNPubA:
    Type: AWS::EC2::Subnet
    Properties:
      MapPublicIpOnLaunch: false
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Select [ 2, !Cidr [ !Select [ 0, !GetAtt DartVPC.Ipv6CidrBlocks], 8, 64 ]] # vamos gerar 8 subnets ipv6 e vamos pegar a terceira
      CidrBlock: 172.35.20.0/24
      VpcId: !Ref DartVPC
      AvailabilityZone: !Select 
        - 0 
        - !GetAZs
          Ref: 'AWS::Region'

  DartSNPubB:
    Type: AWS::EC2::Subnet
    Properties:
      AssignIpv6AddressOnCreation: true
      MapPublicIpOnLaunch: false
      Ipv6CidrBlock: !Select [ 3, !Cidr [ !Select [ 0, !GetAtt DartVPC.Ipv6CidrBlocks], 8, 64 ]] # vamos gerar 8 subnets ipv6 e vamos pegar a quarta
      CidrBlock: 172.35.21.0/24
      VpcId: !Ref DartVPC
      AvailabilityZone: !Select 
        - 1
        - !GetAZs
          Ref: 'AWS::Region'
      
Outputs:
  DartVPC:
    Value: !Ref DartVPC
    Export:
      Name: "DartVPC"
  DartSNPrivA:
    Value: !Ref DartSNPrivA
    Export:
      Name: "DartSNPrivA"
  DartSNPrivB:
    Value: !Ref DartSNPrivB
    Export:
      Name: "DartSNPrivB"
  DartSNPubA:
    Value: !Ref DartSNPubA
    Export:
      Name: "DartSNPubA"
  DartSNPubB:
    Value: !Ref DartSNPubB
    Export:
      Name: "DartSNPubB"
 